server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calculation
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher